# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd6007512952c0f3928e8c2f3650db70243d222e918ac9fca0d7cc4cf0e23e566ad70cea6a69f9f11c1ca385b812e05b1433bfebab8dae1cd5471da96aec6ec3

test:
  secret_key_base: bb098f995357dc13678b3b302dee516cd5134af3f17e7789e0b798f4a65a65fb5f4e1447679c1815d9d77ffd9a390102c1b1f309782209206c135e149d958283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
