# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f885362760452759bbb624f71ac5f26c82a8503bff40f0d07d1611032c5f1f190f1ce7655f4cc392e642628b006250408ba68795c690ff03b2443056d65b379

test:
  secret_key_base: f49b42eb2d2c73f55ef29ecf28ce7137bf8dd9a98a8c70e9314d90a66584598723453323158fa0b83c0a44af3413f2cbe4d35226deeb1b8f181f3c7f088b2b5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
